---
# Source: data-space-connector/charts/postgis/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: data-service-postgis
  namespace: "provider"
  labels:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: data-service-postgis
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgis-16.7.27
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/name: data-service-postgis
    app.kubernetes.io/component: primary
