apiVersion: v1
kind: Service
metadata:
  name: demo-postgres-rest
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports: 
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http-api
  selector:
    app.kubernetes.io/instance: demo-postgres-rest
    app.kubernetes.io/name: demo-postgres-rest