---
# Source: gx-registry/templates/deployment-registry.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gx-registry
  namespace: infra
  labels:
    app.kubernetes.io/name: gx-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gx-registry
  template:
    metadata:
      annotations:
        randstring: "AZtvXjSD"
      labels:
        app.kubernetes.io/name: gx-registry
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: wait-for-kubo
          image: busybox
          command:
            - sh
            - -c
            - until nc -z gx-registry-kubo 5001; do echo waiting for Kubo; sleep 2; done;
        - name: local-trust
          image: quay.io/wi_stefan/gaiax-local-trust:0.0.1
          imagePullPolicy: Always
          env:
            - name: ROOT_CA
              value: "MIIFnDCCA4SgAwIBAgIBATANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJERTEPMA0GA1UECAwGU2F4b255MRAwDgYDVQQHDAdEcmVzZGVuMRMwEQYDVQQKDApGSUNPREVTIENBMRMwEQYDVQQDDApGSUNPREVTLUNBMQswCQYDVQQFEwIwMTAeFw0yNTA0MTAwNjIxMjdaFw0zNTA0MDgwNjIxMjdaMGcxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZTYXhvbnkxEDAOBgNVBAcMB0RyZXNkZW4xEzARBgNVBAoMCkZJQ09ERVMgQ0ExEzARBgNVBAMMCkZJQ09ERVMtQ0ExCzAJBgNVBAUTAjAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkABBFVV5arlEO1MDc+3pmFky4xrmwcDVQGszNuGAOvZgmOiVaN4+BFDFg2vU+HJHHIH0tc63snQuIm0nSiYjORLM8+JDwx1Gt7EZqaVL+8k2PvW3dT6elTpwv/AUn/Keza4qPJF7MzR/IQUWDkVpYkLb7w5bfYDUH3k/jiGtsXPnKlLTpPzOtmIUW3Zarrv7gCCosaf+xWL0GtchWF+7CYMkb6ygdOrcpN/Nk6tYrHHCf44SvzhMzedOKApCj+vp+hchn0XZS9AIuVrCIOZ4J+5fsO0kYrxgbiofJlfSNtagW4qub4WMDTkUFBbzOMMIb+Xstp13mCHisJjAujMulKaCnAWLl8CJWeUFtNXXQzYd+71eSYGE6HMpK3ZdqQbnSu5KIuSzaQA172oOklROA2IHH3VBJsN32dxO+wfwPiEqwC2AvKDftM2EDjoP3tjJ3htn0miGIYfGiy7mqlAsO0nenW5yRB0nSF8UhLR+6nTW0IBTh/dOIQ/OWGJFzsYp5u5Wr/FqhKxQStRCp76j6HMNalWGgv0j4pQUF8ijFv0r/rSbfc6rsEPIuj+sLf3V344c+g27rCTepkG+Xr8wdqoHdkLyimbceCz0WWcmMu02lYOpcUDNMsiSDbrISjzr6n0eulzjFUBrNosQsIskNOQpN6BATBMbB7Q3oIFDep8CAwEAAaNTMFEwHQYDVR0OBBYEFP580SPN8lM/8xQhB9zeYdsXhaUnMB8GA1UdIwQYMBaAFP580SPN8lM/8xQhB9zeYdsXhaUnMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAFZmOYTrDMpn76KA1IR0Ev/cw6fW4Xj2WxWLLpT+SW6q8TOrZ4gs7DwWSHzuydIm9f11XO/oQ4fnGq5f1/Cqju3ZfcHi1/oFJIltixBBh1YKwKmObYedab04K2+UQIe+RuxZkdhL6uILNR4tkBdMW0UPjQbOAnSS9qIUE35vvKx47S/vT65YqoL068g3ZQL19sRZ4f+aPzx+Ad4QmOnAoiWeXKYPrlMS57eCNh4t0cB+YUcTv+fKoDq8zL8yUHc2I9FjF93FDsnQciT4xR4Mu4ItzDFfbv5XdcT7RXMkra58K6El0QK7np4+5r0Q+E36HDpq+lfo3f/QgVdx0Bb75UvzlDSJNcYjW+XuLzU5C1bnf70F6GovLo1891sVlsCc4BfDbxf7RopNE5JPXyCuV7h2GCZP29sGw/l2BxyWlhqZBvQYKXMfHIek1aQPqL4kSjsGZtFDqKy9EJcWC0lA5yZtG+qDxQ57NiKJOQhzva+JDCW9O5u2r9/gGZHOlCV1AG2GvW5pjaqdY1c1rZBInVB/usyeJ82NxQsTt7FXgnOp0/PoaD/XbSNZyxYtdmZNtr+bVzHEyqqJvOAuq2g5WJT4bZyTP4UHyp47RLYLXcq7OyVsmKesPRNx+2fpDh5NAHQHnua4RzRUCVBdBjbp2NImAxpg4DWiVRb5K3fLL1Dn"
          volumeMounts:
            - name: trust-anchor
              mountPath: /out
      containers:
        - name: gx-registry
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: "registry.gitlab.com/gaia-x/lab/compliance/gx-registry:v2.8.1"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: BASE_URI
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: BASE_URL
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: APP_PATH
              value: "/v2"
            - name: evsslonly
              value: "false"
            - name: revocationListURL
              value:
            - name: trustedIssuersURL
              value:
            - name: KUBO_HOST
              value: gx-registry-kubo
            - name: APP_BRANCH
              value: "main"
            - name: ONTOLOGY_VERSION
              value: "development"
            - name: PRIVATE_KEY_ALGORITHM
              value: "PS256"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: HTTPS_PROXY
              value: "http://squid-proxy.infra.svc.cluster.local:8888"
            - name: HTTP_PROXY
              value: "http://squid-proxy.infra.svc.cluster.local:8888"
          envFrom:
            - secretRef:
                name: gx-registry-keypair
          volumeMounts:
            - name: registry-ipfs-data
              mountPath: /data/ipfs
            - name: trust-anchor
              mountPath: /data/ipfs/registry/
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          readinessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          resources: {}
      volumes:
        - name: trust-anchor
          emptyDir: {}
        - name: registry-ipfs-data
          emptyDir: {}
