---
# Source: data-space-connector/charts/postgis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-service-postgis
  namespace: "provider"
  labels:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: data-service-postgis
    app.kubernetes.io/version: 17.6.0
    helm.sh/chart: postgis-16.7.27
automountServiceAccountToken: false
