apiVersion: v1
data:
  client.key.pem: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxSWmpPTy92Z2xQRW92RTRHRnRUUGhndkVqWXZHSHlnYzFJSUtLUDdQQm5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFRElFeTAzWFdLVHltTDNBRWN4TXJmOE1oK0g5VXJ4c2pDcmFSUEIxeWdjNithdGdSYjZOegplN3liOVJqdUtodGVMSzAxK1JIRTh2ZEx0M0d6eThrTU5RPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: signing-key
  namespace: provider
