apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-walt-wallet-api
  namespace: {{ $.Release.Namespace | quote }}
data:
  _features.conf: |
    enabledFeatures = [
      "trusted-ca"
    ]

  trusted-ca.conf: |
    certificates = [
      "-----BEGIN CERTIFICATE-----\nMIIGKjCCBBKgAwIBAgIUAXPiPDpOoRbySWkD3/F+7pNuV08wDQYJKoZIhvcNAQEL\nBQAwgY4xCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZTYXhvbnkxEDAOBgNVBAcMB0Ry\nZXNkZW4xEDAOBgNVBAoMB0ZJQ09ERVMxDDAKBgNVBAsMA0RldjEbMBkGA1UEAwwS\nKi4xMjcuMC4wLjEubmlwLmlvMR8wHQYJKoZIhvcNAQkBFhBmaWNvZGVzQGZkc2Mu\nb3JnMB4XDTI0MTEwMTEyMTYzMVoXDTM0MTAzMDEyMTYzMVowgasxCzAJBgNVBAYT\nAkJFMREwDwYDVQQIDAhCUlVTU0VMUzERMA8GA1UEBwwIQnJ1c3NlbHMxHjAcBgNV\nBAoMFUZhbmN5IE1hcmtldHBsYWNlIENvLjEMMAoGA1UECwwDT3BzMSIwIAYDVQQD\nDBl3d3cuZmFuY3ktbWFya2V0cGxhY2UuYml6MSQwIgYJKoZIhvcNAQkBFhVmYW5j\neUBtYXJrZXRwbGFjZS5iaXowggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC\nAQC3+u4quOVw+tuWd7ZhVj4QSATb26Scvq6zeHPvs4slka0Hy0g33+4egPBl+Pto\nzOzy5OA/1lhBsP/ErI5vMKAesULpRM9SGI1YpDvFWS4ocmGsdadBREee++sszWOy\n+lG/lE8Pbe6UDw1D3c0mFE3GfZ+Iyx2E8t8RkjKpUC9ZZ65d6pWHaYpxU8q+VOr7\n1doVAfw4WnZc9I6i2ls00WIRDdGgjIJK81G+gjxfMJUoyHX7KbtSirzj/0SYePnt\nMVlVz5D9A/ZkL/hhCMoFQAxt7NKE5FdTTYK8NtEekBiwNxy18udbk/hBD4pNY84w\nLwTWUXHn8woH2ixGZhTugxQ4YTGzZ6UU2DXpDeb+JW/b6B+PUtYpe5JSVTEhpW4p\nA3n6jSk3AQFprCMR85mUGjJWCWE5Ctf7awcRZ+10gqfzuFxjKFyzawVVFKx6eUo5\nCFS9Br1V+PnLpeWsxzuFXrB060PuO2IBYIWlB9AcRe+actrXA0+MF2engQPnm4ii\n9B7tvfiI+OAUojZfrZ2GxOGo+rr1TSpjcaBfhsB/iT68l4yCYJ99N7yx27MVaWAK\nSVv4de/VYa4v1OXkrOthD5zxcVFo8L1TTec1hU9ItINv6FmxMbOztzBjE1fP0zG3\n2B+R+uCptHrbYbzlXvBotunKaqvFat3vU9ZlVtZJ1u9YqwIDAQABo2EwXzAdBgNV\nHREEFjAUghIqLjEyNy4wLjAuMS5uaXAuaW8wHQYDVR0OBBYEFCsMqME0SLkgohDP\ngCQ0uprsJjwPMB8GA1UdIwQYMBaAFPYWvr3QjEK7Si2mKhlxalcsuiHHMA0GCSqG\nSIb3DQEBCwUAA4ICAQCAtCwRjZlcftNenjQ/OeOsrTxRSVLO8VAlYIc3VzBN9hF1\n6S9LOckjszSmp9GsNEKvHN4KMecpABjTlpnMW7/zrFVqP9IAu/3Zd46JiJCMvZsQ\nn9MTgGQWDJq/OrCMIPEEzXiNemRL1uo2YEuDv9Uc87QqWVEIAooSuVp8Rd3WjEqi\neh9vt1HQ4gooOeVJcvG/TQWE11EOaC/lKiKdBgJ81FXIDgLu46dfBSpMvVg88FLp\nW/xmPgPPc7jVmxVRwSv3Kq5Pe506gDFa8k9ERZH20tXXkzuZJ9z3+fhp0vI6srDh\nFIe1NsQokw0fNNO5BIMCBsYwr+q5qR5N9a7f2wTW2ssZfZ+79C4wl6XGy+RPiPDt\nb0dOLjNeJQ1Nb9c1U5ViR3yTIxEasXHigsZG0a9BsWsDmLp8ZZL3XbjBsxAEnZqj\nngob+5E2Fj9Bu7ZrU4IRHJAdOk7sduZ/fgSUu4KfIFN1zOCSvqSJeQt0J59N1y94\nTHAgjGBGof+ooE+rXaCw5RGGE3xr7+xozh2iqFwi8Nycae5avYy4pZzVtAe0+Bu+\nfpDaGo14AT1wpEMEb8WzxH95JO5ey6albbZqVgrzA/Ek21KCwOrBkt61EMyp4iW1\nAU25BeTHIdj0Y2uLJW1IadZ8GivItuVp2AS1n9ysr5s4B+hUegNIViVBAPUcNA==\n-----END CERTIFICATE-----\n"
    ]

  walt.yaml: |
    hikariDataSource:
      jdbcUrl: jdbc:sqlite:/data-sqlite/data.db
      maximumPoolSize: 5
      autoCommit: false
      dataSource:
        journalMode: WAL
        fullColumnNames: false

  db.conf: |
    dataSource {
      jdbcUrl = "jdbc:sqlite:/data-sqlite/data.db"
      driverClassName = "org.sqlite.JDBC"
      username = "waltid"
      password = "waltid"
      transactionIsolation = "TRANSACTION_SERIALIZABLE"

      maximumPoolSize = 16
      minimumIdle = 4
      maxLifetime = 60000
      autoCommit = false
      dataSource {
          journalMode = WAL
          fullColumnNames = false
      }
    }

  db.sqlite.conf: |
    hikariDataSource {
      jdbcUrl = "jdbc:sqlite:/data-sqlite/data.db"
      driverClassName = "org.sqlite.JDBC"
      username = ""
      password = ""
      transactionIsolation = "TRANSACTION_SERIALIZABLE"

      maximumPoolSize = 5
      autoCommit = false
      dataSource {
          journalMode = WAL
          fullColumnNames = false
      }
    }
    recreateDatabaseOnStart = false
    
  web.conf: |
    webHost = "0.0.0.0"
    webPort = 4545
  #logins.conf: |
  #  enabledLoginMethods: [
  #    "email"
  # ]

  oidc.conf: |
    publicBaseUrl = "https://wallet.io"
    providerName = keycloak
    oidcRealm = "https://keycloak.wallet.io/realms/waltid-keycloak-ktor"
    oidcJwks = "${oidcRealm}/protocol/openid-connect/certs"
    authorizeUrl = "${oidcRealm}/protocol/openid-connect/auth"
    accessTokenUrl = "${oidcRealm}/protocol/openid-connect/token"
    logoutUrl = "${oidcRealm}/protocol/openid-connect/logout"
    clientId = "wallet_backend_prod"
    clientSecret = "__DEFAULT_KEYCLOAK_CLIENT_SECRET__"
    keycloakUserApi = "https://keycloak.wallet.io/admin/realms/waltid-keycloak-ktor/users"
    jwksCache = {
        cacheSize = 10
        cacheExpirationHours = 24
        rateLimit: {
            bucketSize: 10
            refillRateMinutes: 1
        }
    }

  auth.conf: |
    encryptionKey = "dncygwnvivxzlohc" //<128 bit -- key> a 128 bit (16 chars) key
    signKey = "jyjeylmidlylokzh" //<128 bit -- key> a 128 bit (16 chars) key

    # Available Signing Algorithms are: RS256 or HS256.
    # If HS256, then provide the 256+ bit key in the tokenKey field. If RS256, then provide the private key in JWK format in the tokenKey field.
    ;tokenKey = "<a - longer 256+ bit key or rsa private key in jwk format- here>" // at least 256 bit (32 chars)

    # Examples:
    ; tokenKey = "hjklwcptiniwjkdwwkigreumcayoyiso"
    tokenKey = "{"p":"8DhAtwXUO8as8-jY_e0OIX2tB8TmoLkLTwJtJXmWrE7pFUVFMviXCHiNd3x_KngJel002xGW3zTHweSqVIkKO_0HqSEed9XKrKQnJTypU5_M-lDHNUtYTp6ATB-rjuGL8F-BxjoMZUTq5arUQ8IxHJda0iQSqwIH-8F-ivHpO2U","kty":"RSA","q":"xoPLLuoXVh9Wk4m8cTXhLf-RA9lapIKhwoPadRJSA8ceA1dqhsH1Vjgk0UVxV1nc-LJUBvpPsWuJDoDc7SUPNZR79Z2UyXZXBBMnXx82UOuK_wJ6yi111rLUDgeHZhh67MAL0TSX6Pje1Xl2s--i7UQuOba6P06SFrl81S--mGM","d":"TSmJ37dU1yZ7NSfL3hm6yfFPCtjww0D4t6uiy8KTpi3Oy7C8_vx1HFZLPr6AlDJkIGfOvHAJ87gVexguJGQgmhu0VJzEsH4IXiVx9L8aNqloc6umhS44dLZU6mwr5EVhx3jz0qI3t6CORzzs6BNnzLtUCIErwpFLDzyI9T0-vxivIBlG4pjmJL0I0zpirMGg-E2oYYIYWgRAc6teibQ5auS3skxIJINBOiAKhvQGU1uOxRnPHiGzEk-sStwrgBbCmlWFy4xXBymkUZTpPwW-dqCpxIUXcfDI-AQ85XmdWoOZRvX5YpX5BDdkeHy1Og3GAsf7w8BCQeROv6fnLEgVPQ","e":"AQAB","kid":"44benLH7kwpQ5uynsoM8JkhftDR6QYpAxVeVm5i-Cqw","qi":"Nw-UbUD9eBIEUJr_y2VkIi1zzrFY19DU3842PRY7sal4pUO1OSO65v5KJwxRsww-k4oD2IrJM1vwCOYXMOkGadldpYDbHZcZAXd4MMfLrrmNKS7eP60m36n5WUookGOowqhLScCYlArYF7JcptN2E77-gRFGf-Yo7KRJA8Q0TYI","dp":"uB31hBJErBhIAZ6rilyCYysHTxgcyH1r7H_oljuOP70vqyzvr_SXFlgH3dgfQ7bDVPVRiML_h07V-IfCAY8TuAzlLT2EM8c6U35xvnmzMrQdkJIPTYrVQVT88tunS5kWAAPD3OIrFAdxntyDWvfhWo-rfbtGT6n74ntY-TgXUn0","dq":"s2Iit6kXH17AKCAdpZuPeLZo_zZovyHANHpbbND6RamniFN00oLwRFIFiwmaStnMYPscDRYh72wB9JYjjTOg08TyYtdbvNTv-qGoQT9-II9IEfnWpV2BD1qXXnoVMv_KDKfZxdklsIM7MWJKDnzsGEU1FDf3gv9n6ZsBn88-Bos","n":"ukctf01ANV4BiJ3eBdoqepmTh1CspUkzKK3zFa2kfUM2O1HMGrNUoJYyUZOFTcrPATOils1I27zGkYeLOYVHQn-QM4kjXDB_OxTpczYOkSu2s50QBk5jTAIb2pLC8ynnDAQWAXFzVOyT_e_PY3crhnosI900tzvyjtAhb8BxIAe7co7OCScagv8A2MOcm-3I9LsM_ecjM5ACfNpOwPzrxPgQzKp3vZapBVLOp1LqiKuyf1_1gTGMmr17MnliPoMo-jiQQaaU-DE-rnuARTabE05b7TqdK2WXFWnXnIRxwoklbZajXJY5EqeMlbt4FNVfmtFC7FXv_3GGUCNoqGvwDw"}"
    audTokenClaim = "https://wallet.127.0.0.1.nip.io:8443"
    issTokenClaim = "https://wallet.127.0.0.1.nip.io:8443"
    tokenLifetime = "30"//days

  nitro.json: |
    {
      "date": "2024-11-28T13:22:09.485Z",
      "preset": "node-server",
      "framework": {
        "name": "nuxt",
        "version": "3.14.1592"
      },
      "versions": {
        "nitro": "2.10.4"
      },
      "commands": {
        "preview": "node ./server/index.mjs"
      },
      "config": {
        "devProxy": {
            "/wallet-api/": "https://wallet.127.0.0.1.nip.io:8443/wallet-api"
        }
      }
    }