---
# Source: data-space-connector/templates/data-plane-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: data-service-secret
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
data:
  postgres-user-password: "Wk0wRjE4UWZkNU9uSDVtZ2FJUzBrYWhsekI5VnVI"
  postgres-admin-password: "ajNVUHJ3VEZ3NzZUQlNDUDUwTHpzTGRNUDhkSmsz"
