---
# Source: data-space-connector/templates/database-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: database-secret
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
data:
  postgres-user-password: "UHphTkhycTVPT1RvRWVja0F6b0tHVU1qSDh2amFE"
  postgres-admin-password: "Z09wUTh0cEYyeXVpdnJ1c2dyT2lXend1Y0cyanVX"
