---
# Source: data-space-connector/templates/issuance-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: issuance-secret
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
data:
  postgres-user-password: "WUlFQjVEZ3NUa0liRHRpd3lIa2NkYnJsamhMMHRW"
  postgres-admin-password: "NTU3OHVCWmNHSTd2bGx1bHk5bE52blJVUXNuYm9B"
  keycloak-admin: "cmUwZ0Y2dEVYMEdkb29oYTA5WEF2RkRMYjFhT3Nn"
  store-pass: "WFlwUTR0MXZvMXl2bW9xZ3pkdmc0SlYzRWQ1WUhP"
