---
# Source: data-space-connector/templates/marketplace-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: marketplace-secret
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
data:
  mongodb-root-password: "cEZoTU90ZjJacDRiMHlFNnRCZGN5b0t6ZUk1a1ow"
  mongodb-password: "U2lKNU5QdDY1Q2NKSUYzNE1adVp0cHpGQzY4a0ox"
