---
# Source: data-space-connector/templates/marketplace-env-var-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: marketplace-secret-env
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
data:
  MONGO_BAE_BELP_PW: "M1BNS3pESU9lbExXTno1R09rZmJhVE5xYVZ2b1I5"
  MONGO_BAE_CHARGING_PW: "SUFia01MT0NjVEhxWlVlYk51UTlxdFBWdjRBZUhn"
