---
# Source: data-space-connector/templates/opa-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata: 
  name: opa-config
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
data:
  opa.yaml: |-
    services:
      - name: bundle-server
        url: http://odrl-pap:8080/bundles/service/v1
    bundles:
      policies:
          service: bundle-server
          resource: policies.tar.gz
          polling:
            min_delay_seconds: 2
            max_delay_seconds: 4
      methods:
          service: bundle-server
          resource: methods.tar.gz
          polling:
            min_delay_seconds: 1
            max_delay_seconds: 3
      data:
          service: bundle-server
          resource: data.tar.gz
          polling:
            min_delay_seconds: 1
            max_delay_seconds: 15
    default_decision: /policy/main/allow
