---
# Source: data-space-connector/templates/rainbow-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rainbow
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: rainbow
      app.kubernetes.io/instance: consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rainbow
        app.kubernetes.io/instance: consumer
    spec:
      serviceAccountName: default
      initContainers:
        - name: rainbow-init
          imagePullPolicy: Always
          image: quay.io/wi_stefan/rainbow:0.0.3
          args: [ "provider", "setup" ]
          env:
            - name: DB_URL
              value: postgresql
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-admin-password
            - name: DB_DATABASE
              value: rainbow
            - name: DB_TYPE
              value: postgres
            - name: DB_PORT
              value: "5432"
      containers:
        - name: rainbow
          imagePullPolicy: Always
          image: quay.io/wi_stefan/rainbow:0.0.3
          args: [ "provider", "start" ]
          env:
            - name: DB_URL
              value: postgresql
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-admin-password
            - name: DB_DATABASE
              value: rainbow
            - name: DB_TYPE
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: HOST_URL
              value: "0.0.0.0"
          ports:
            - containerPort: 1234
              name: http
      volumes:
        - name: ccs-registration
          configMap:
            name: rainbow-registration
            defaultMode: 0755
