apiVersion: v1
kind: Service
metadata:
  name: demo-wallet
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports: 
    - name: static
      port: 8080
      protocol: TCP
      targetPort: static
    - name: https
      port: 8443
      protocol: TCP
      targetPort: static
  selector:
    app.kubernetes.io/instance: demo-wallet
    app.kubernetes.io/name: demo-wallet