---
# Source: data-space-connector/charts/contract-management/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: contract-management
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: contract-management
    helm.sh/chart: contract-management-3.2.0
    app.kubernetes.io/instance: provider
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: contract-management
    app.kubernetes.io/instance: provider
