---
# Source: data-space-connector/charts/marketplace/templates/biz-ecosystem-logic-proxy/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssc
  namespace: "provider"
  labels:
    
    component: "biz-ecosystem-logic-proxy"
    app: marketplace
    release: provider
    chart: marketplace-0.11.21
    heritage: Helm
