---
# Source: data-space-connector/charts/apisix/charts/etcd/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: provider-etcd
  namespace: "provider"
  labels:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    app.kubernetes.io/version: 3.5.16
    helm.sh/chart: etcd-10.2.18
    app.kubernetes.io/component: etcd
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: "client"
      port: 2379
      targetPort: client
      nodePort: null
    - name: "peer"
      port: 2380
      targetPort: peer
      nodePort: null
  selector:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/name: etcd
    app.kubernetes.io/component: etcd
