---
# Source: data-space-connector/charts/marketplace/templates/biz-ecosystem-charging-backend/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: provider-biz-ecosystem-charging-backend
  namespace: "provider"
  labels:
    
    component: "biz-ecosystem-charging-backend"
    app: marketplace
    release: provider
    chart: marketplace-0.11.21
    heritage: Helm
type: Opaque
data:
  dbPassword: cGFzcw==
