---
# Source: data-space-connector/charts/vcverifier/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: verifier
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: vcverifier
    helm.sh/chart: vcverifier-4.1.2
    app.kubernetes.io/instance: provider
    app.kubernetes.io/version: "6.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: backend
      protocol: TCP
  selector:
    app.kubernetes.io/name: vcverifier
    app.kubernetes.io/instance: provider
