apiVersion: v2
name: demo-walt
description: Walt deployment
version: 0.0.1

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5