---
# Source: data-space-connector/charts/keycloak/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-keycloak
  namespace: "provider"
  labels:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.1.5
    helm.sh/chart: keycloak-24.5.2
    app.kubernetes.io/component: keycloak
automountServiceAccountToken: false
