---
# Source: data-space-connector/charts/keycloak/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: provider-keycloak
  namespace: "provider"
  labels:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.1.5
    helm.sh/chart: keycloak-24.5.2
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      nodePort: null
  selector:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
