---
# Source: gx-registry/templates/deployment-registry.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gx-registry
  namespace: infra
  labels:
    app.kubernetes.io/name: gx-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gx-registry
  template:
    metadata:
      annotations:
        randstring: "AZtvXjSD"
      labels:
        app.kubernetes.io/name: gx-registry
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: wait-for-kubo
          image: busybox
          command:
            - sh
            - -c
            - until nc -z gx-registry-kubo 5001; do echo waiting for Kubo; sleep 2; done;
        - name: local-trust
          image: quay.io/wi_stefan/gaiax-local-trust:0.0.1
          imagePullPolicy: Always
          env:
            - name: ROOT_CA
              value: "MIIFnDCCA4SgAwIBAgIBATANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJERTEPMA0GA1UECAwGU2F4b255MRAwDgYDVQQHDAdEcmVzZGVuMRMwEQYDVQQKDApGSUNPREVTIENBMRMwEQYDVQQDDApGSUNPREVTLUNBMQswCQYDVQQFEwIwMTAeFw0yNTA5MDQwODIzNTJaFw0zNTA5MDIwODIzNTJaMGcxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZTYXhvbnkxEDAOBgNVBAcMB0RyZXNkZW4xEzARBgNVBAoMCkZJQ09ERVMgQ0ExEzARBgNVBAMMCkZJQ09ERVMtQ0ExCzAJBgNVBAUTAjAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsAZPrQa4rmfhdNSbFBtU2B5batwEAysu4rv6XitYyo7rNXpmt3T1+nFoDInOOqN0THYZit8fkGnamUZHvmMwwc1RF6j3CKQpy6jAXNTZAjckO6GSEH4tEqgQmhWQpiwT69HXLiltaBxjQq0M1rCF95K9+OksjkhkDoQCFXoHPm3UyW/4KOy7z6bw7xjTyQLS1GYI6vzBlG5xIUBXQi6h1u3LI9aGQV5u+cs6GYnsJVkcdjC3tIxCbUmXsK5hspe78d7j+bX2goHv+9b6xJk9yxzwJlHBS/fbki0RRMdCRXQiYuYRnIjRf5v6oNzF/sTqtsWiqmkQGyxoWBXddeH0ZDm5JCvcPvFPIBhX8EA2/5Hm618zAfBbpgRErt1w2VPzktMBrDu9jA+AlRKL8BXoSmghPxZRH/uEzzu6OqtNKesZzWaTFv07sa8kQCwiJsqa1heXtkvpX9+1gHE7uREklQloj9LsQHhBOAxbLwVJMmO0DQeJ2CcuwwSiFzJMRRHsi/Plz+qlg8iQQIYLLB0J0YT595eavsUtSDopy2pkOKYV7d6uEoCD1kRQTz4jvjcW7/aY2YGBi2+wcluR4cvEF4j8W3qgP6cSOq239Ctr5MDc50a8WDfgLsqhEJ7MEzgP/Q0/6vMeuWbbAF3QRqbWBIeNB260EjAJAZI9DRNDfFUCAwEAAaNTMFEwHQYDVR0OBBYEFKbrAKNRYEN1TATjLULr+sWACaP+MB8GA1UdIwQYMBaAFKbrAKNRYEN1TATjLULr+sWACaP+MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBADqzvjTL9/OBdeIY/IMTzYRNIof5vStoylfP6MWbT3zPe+oIK6x+KDI/V+wDH5/WLQWoU22iGrx3zIJ3Eu4fcRT031pKLbbXu6FpoBuuJX7e2qnfh8WQNoee4EAAfw/np7TuhWkK+iGSgoRJCiY9SCqW7yXQ93ukUB4pFWeYvmzGxB+nVbY344iyBfvYmbfeokG25kwL7Jo2lUvBOzUejO9n1TlSiPQpoxyfdfijj3zhPgOavYB+4TU45iO5EfF+nIMm1HvjKkK3lmHRC5WITLCBP/shNQhCEFXW6uYtqyfx2vlq3gD552WR55qL78SDfDllvqqL+spQx4NA1awGTVEOP0hfni+wJ8dLNiCta1RwfmW8AtPsrGaa4BHJykmheL0k1kkPI3ztTErf2ungkTgv87cLslxUP8cvMGqhSV9ErMOotHyKimQoAdTfcpiiX3jxAJWpieAqW9A87Ei5HrE6EOw3FzvzfFO49vWv9KEWqcG9MB9KqKh/A2Foxh5b5AfloZAs7Djif47OPhWjxZoaRKTniX099nrvr++KqorTWzOi5BcnA8ozKXDQhPgBiR1p+OXzlqL2cf/ckWLHCmlIy2G7JAJvwfhiC8kt/tx6Wg2jXD0Ktm7Da1gtdSwyUFR7llznQwMh5b33+iERS11o0a7KXLiFQaefBnWVmuX6"
          volumeMounts:
            - name: trust-anchor
              mountPath: /out
      containers:
        - name: gx-registry
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: "registry.gitlab.com/gaia-x/lab/compliance/gx-registry:v2.8.1"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: BASE_URI
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: BASE_URL
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: APP_PATH
              value: "/v2"
            - name: evsslonly
              value: "false"
            - name: revocationListURL
              value:
            - name: trustedIssuersURL
              value:
            - name: KUBO_HOST
              value: gx-registry-kubo
            - name: APP_BRANCH
              value: "main"
            - name: ONTOLOGY_VERSION
              value: "development"
            - name: PRIVATE_KEY_ALGORITHM
              value: "PS256"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: HTTPS_PROXY
              value: "http://squid-proxy.infra.svc.cluster.local:8888"
            - name: HTTP_PROXY
              value: "http://squid-proxy.infra.svc.cluster.local:8888"
          envFrom:
            - secretRef:
                name: gx-registry-keypair
          volumeMounts:
            - name: registry-ipfs-data
              mountPath: /data/ipfs
            - name: trust-anchor
              mountPath: /data/ipfs/registry/
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          readinessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          resources: {}
      volumes:
        - name: trust-anchor
          emptyDir: {}
        - name: registry-ipfs-data
          emptyDir: {}
