---
# Source: data-space-connector/templates/data-plane-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: data-service-secret
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
data:
  postgres-user-password: "cnNPMnhRSjFVaTdjRWoxelRNcXV5YUp0azZLUXIx"
  postgres-admin-password: "RU1KV0c4eXEyZE10YzA5REZFcmtEaGJDUzkxU21p"
