---
# Source: data-space-connector/templates/issuance-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: issuance-secret
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
data:
  postgres-user-password: "S2M1ajFseDk1V1IySlJpYVNOU255aWJSV2JHeThS"
  postgres-admin-password: "TXVZZ2xoaGJ2WkJWb1ZwblhCWUNlMDZORmFiVmU3"
  keycloak-admin: "OHo4UjJ6VTBWR2tReXFRSllvcGtyTnZpVVY2OFRM"
  store-pass: "Z1FyajNrRFhKQXhXUlQydkxua25zOElPbGdmdWU0"
