---
# Source: data-space-connector/templates/marketplace-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: marketplace-secret
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
data:
  mongodb-root-password: "MUZOblVPWUQ3Q0hodjdjbHF3b2pWQlpReE15MHhi"
  mongodb-password: "b1U0UzNyR0xWNVBOVGFrcG5La29NTG9GZzRValFy"
