apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gx-cloud-wallet.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "gx-cloud-wallet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gx-cloud-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        randstring: {{ randAlphaNum 8 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gx-cloud-wallet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ include "gx-cloud-wallet.fullname" . | trunc 10 | trimSuffix "-"}}-http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ (first (first .Values.ingress.hosts).paths).path }}
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: {{ (first (first .Values.ingress.hosts).paths).path }}
              port: {{ .Values.service.port }}
          env:
            - name: BASE_URL
              {{- with (first .Values.ingress.hosts) }}
              value: "https://{{ .host }}{{ (first .paths).path}}"
              {{- end}}
            - name: STORAGE
              value: {{ .Values.STORAGE }}
            - name: S3_ACCESS_KEY_ID
              value: {{ .Values.S3_ACCESS_KEY_ID }}
            - name: S3_SECRET_ACCESS_KEY
              value: {{ .Values.S3_SECRET_ACCESS_KEY }}
            - name: S3_ENDPOINT
              value: {{ .Values.S3_ENDPOINT }}
            - name: S3_REGION
              value: {{ .Values.S3_REGION }}
            - name: S3_BUCKET_NAME
              value: {{ .Values.S3_BUCKET_NAME }}
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: {{ include "gx-cloud-wallet.fullname" . }}-secrets
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: public
                  name: {{ include "gx-cloud-wallet.fullname" . }}-secrets
            - name: APP_PATH
              value: "{{ (first (first .Values.ingress.hosts).paths).path }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}