---
# Source: trust-anchor/templates/secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-database-secret
  namespace: "trust-anchor"
  labels:
    
    app.kubernetes.io/name: trust-anchor
    helm.sh/chart: trust-anchor-0.2.0
    app.kubernetes.io/instance: trust-anchor
    app.kubernetes.io/managed-by: Helm
data:
  mysql-root-password: "UngyQXdnVTZtWVJhQUNMdUZrSG8zdVNzNDJ2dXEx"
  mysql-replication-password: "MHhqZXROWmc4aTFBSHNhVkNnT2o1NDhrTm9DQ29X"
  mysql-password: "SVhaRXJzdlNqNndaNnB0Zjl1WTY1UDIwaUdDQXcw"
