ingress:
  enabled: true
  host: wallet.127.0.0.1.nip.io

image:
  repository: registry.gitlab.com/tno-tsg/dataspace-protocol/tno-security-gateway/wallet
  tag: "v0.10.0"
replicaCount: 1


#resources:
#  requests:
#    memory: "200Mi"
#    cpu: "100m"
#  limits:
#    memory: "350Mi"
#    cpu: "1150m"

serviceAccount:
  create: false

env: []
configFromSecrets: {}

subPath: ""

config:
  server:
    port: 3000
    listen: "0.0.0.0"
    publicDomain: "wallet.127.0.0.1.nip.io"
    publicAddress: https://wallet.127.0.0.1.nip.io/
  db:
    type: postgres
    database: wallet
    host: postgresql
    port: 5432
    username: postgres
    password: password
  auth:
    enabled: false
    openIdConfigurationURL: "https://{{ .Values.host }}/.well-known/openid-configuration"
    callbackURL: https://{{ .Values.host }}{{ template "tsg.subPath" $ }}/api/auth/callback
    redirectURL: https://{{ .Values.host }}{{ template "tsg.subPath" $ }}/
    rolePath: "$.roles[*]"
    clientId: test-client
    clientSecret: secret
  runtime: 
    color: "#3B8BF6"
# -- configuration for the postgresql to be deployed as part of the connector, see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for all options
postgresql:
  # -- should it be enabled? set to false if one outside the chart is used.
  enabled: true
  image:
    # -- fixes the unpullable image referenced in the chart
    tag: 13.18.0
  # -- allows to set a fixed name for the services
  fullnameOverride: postgresql
  # -- configure authentication to mysql
  auth:
    # -- key of the secrets inside the secret      
    user: "user"
    postgresPassword: "password"
    password: "password"
    replicationPassword: "password"

  readReplicas:
    persistence:
      enabled: false

  # -- configuration for the primary of the db
  primary:
    persistence:
      enabled: false
    # -- scripts to be run on intialization
    initdb:
      scripts:
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE wallet;"
