{{- $wapi := index .Values "wallet" "wallet-api" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallet-api.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: wallet-api
    app.kubernetes.io/instance: infra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wallet-api
      app.kubernetes.io/instance: infra
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallet-api
        app.kubernetes.io/instance: infra
    spec:
      serviceAccountName: wallet-api
      securityContext:
        {}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - java
            - -Djavax.net.ssl.trustStore=/temp/cacerts 
            - -Djavax.net.ssl.trustStorePassword=changeit
            - -jar
            - /app/in2-wallet-api.jar
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $wapi.image.repository }}:{{ $wapi.image.tag }}"
          imagePullPolicy: {{ $wapi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $wapi.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ $wapi.livenessProbe.path }}
              port: {{ $wapi.app.internalServerPort }}
            initialDelaySeconds: {{ $wapi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $wapi.livenessProbe.periodSeconds }}
            failureThreshold: {{ $wapi.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ $wapi.readinessProbe.path }}
              port: {{ $wapi.app.internalServerPort }}
            initialDelaySeconds: {{ $wapi.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $wapi.readinessProbe.periodSeconds }}
            failureThreshold: {{ $wapi.readinessProbe.failureThreshold }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{$wapi.app.profile}}
            - name: LOGGING_LEVEL_ES_IN2_WALLET_API
              value: {{$wapi.app.logLevel}}
            - name: SPRING_WEBFLUX_BASEPATH
              value: {{$wapi.app.basePath}}
            # AUTH SERVER
            - name: AUTH_SERVER_EXTERNAL_URL_SCHEME
              value: {{$wapi.app.authServer.external.scheme}}
            - name: AUTH_SERVER_EXTERNAL_URL_DOMAIN
              value: {{$wapi.app.authServer.external.domain}}
            - name: AUTH_SERVER_EXTERNAL_URL_PORT
              value: {{quote $wapi.app.authServer.external.port}}
            - name: AUTH_SERVER_EXTERNAL_URL_PATH
              value: {{$wapi.app.authServer.external.path}}
            - name: AUTH_SERVER_INTERNAL_URL_SCHEME
              value: {{$wapi.app.authServer.internal.scheme}}
            - name: AUTH_SERVER_INTERNAL_URL_DOMAIN
              value: {{$wapi.app.authServer.internal.domain}}
            - name: AUTH_SERVER_INTERNAL_URL_PORT
              value: {{quote $wapi.app.authServer.internal.port}}
            - name: AUTH_SERVER_INTERNAL_URL_PATH
              value: {{$wapi.app.authServer.internal.path}}
            - name: AUTH_SERVER_JWT_DECODER_PATH
              value: {{$wapi.app.authServer.jwtDecoderPath}}
            # BROKER
            - name: BROKER_PROVIDER
              value: {{$wapi.app.broker.provider}}
            - name: BROKER_INTERNAL_URL_SCHEME
              value: {{$wapi.app.broker.internal.scheme}}
            - name: BROKER_INTERNAL_URL_DOMAIN
              value: {{$wapi.app.broker.internal.domain}}
            - name: BROKER_INTERNAL_URL_PORT
              value: {{quote $wapi.app.broker.internal.port}}
            - name: BROKER_PATHS_ENTITIES
              value: {{$wapi.app.broker.pathsEntities}}
            # VAULT
            - name: VAULT_PROVIDER_NAME
              value: {{$wapi.app.vault.provider}}
            - name: HASHICORP_VAULT_HOST
              value: {{$wapi.app.vault.host}}
            - name: HASHICORP_VAULT_SCHEME
              value: {{$wapi.app.vault.scheme}}
            - name: HASHICORP_VAULT_PORT
              value: {{quote $wapi.app.vault.port}}
            - name: HASHICORP_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wallet-api-token-secret
                  key: token
          volumeMounts:
            - mountPath: "/temp"
              name: cacerts
            - mountPath: "/opt/openjdk-17/lib/security/cacerts"
              name: cacerts
              subPath: cacerts
      volumes:
        - name: cacerts
          configMap:
            name: cacerts