---
# Source: data-space-connector/charts/mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: "provider"
  labels:
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/version: 8.0.10
    helm.sh/chart: mongodb-16.5.21
secrets:
  - name: marketplace-secret
automountServiceAccountToken: false
