name: Test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Ensure br_netfilter is enabled.
        run: |
          sudo modprobe br_netfilter

      - uses: azure/setup-kubectl@v4

      - name: Execute tests
        id: test        
        continue-on-error: true
        run: |
          mvn clean integration-test -Ptest
      
      - name: Debug error
        id: debug
        run: | 
          export KUBECONFIG=$(pwd)/it/target/k3s.yaml
          kubectl get pods -n provider --field-selector=status.phase!=Running -o json | jq -r '.items[].metadata.name' | xargs -I {} sh -c 'echo "=== Describe: {} ==="; kubectl describe pod {} -n provider; echo "=== Logs: {} ==="; kubectl logs {} -n provider; echo;'

