name: Test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Ensure br_netfilter is enabled.
        run: |
          sudo modprobe br_netfilter

      - name: Execute tests
        continue-on-error: true
        id: test        
        run: |
          mvn clean integration-test -Ptest

      - uses: azure/setup-kubectl@v4
        id: install

      - name: Logs
        run: |
          echo pwd
          echo Next
          ls target/
          export KUBECONFIG=./target/k3s.yaml
          kubectl logs -n provider -l app.kubernetes.io/name=odrl-pap
          kubectl logs -n provider -l app.kubernetes.io/name=rainbow
          kubectl logs -n provider postgresql-0
          